/* Resource Datei Indizes fÅr NVLANG */

#define POPUP            0   /* Formular/Dialog */
#define PANEL            0   /* BOX in Baum POPUP */
#define ENGLISH_US       1   /* STRING in Baum POPUP */
#define GERMAN           2   /* STRING in Baum POPUP */
#define FRENCH           3   /* STRING in Baum POPUP */
#define ENGLISH_UK       4   /* STRING in Baum POPUP */
#define SPAIN            5   /* STRING in Baum POPUP */
#define ITALIAN          6   /* STRING in Baum POPUP */
#define SWEDISH          7   /* STRING in Baum POPUP */
#define FRENCH_SW        8   /* STRING in Baum POPUP */
#define GERMAN_SW        9   /* STRING in Baum POPUP */
#define TURKEY           10  /* STRING in Baum POPUP */
#define FINISH           11  /* STRING in Baum POPUP */
#define NORWEGIAN        12  /* STRING in Baum POPUP */
#define DANISH           13  /* STRING in Baum POPUP */
#define SAUDIARABIA      14  /* STRING in Baum POPUP */
#define NETHERLAND       15  /* STRING in Baum POPUP */
#define CZECH            16  /* STRING in Baum POPUP */
#define HUNGARIAN        17  /* STRING in Baum POPUP */
#define RUSSIAN          18  /* STRING in Baum POPUP */
#define GREEK            19  /* STRING in Baum POPUP */

#define NVSELECT         1   /* Formular/Dialog */
#define LANG             3   /* BUTTON in Baum NVSELECT */
#define KBD_LANG         4   /* BUTTON in Baum NVSELECT */
#define OK               5   /* BUTTON in Baum NVSELECT */
#define CANCEL           6   /* BUTTON in Baum NVSELECT */

#define TEST             2   /* Formular/Dialog */
